version: '3.7'

services:
    ##### DATA STORES #####
    mongodb:
        container_name: mongodb
        image: mongo:3.4
        networks:
            - backend
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=demo-staging-secret
            - TZ=Asia/Bangkok
        volumes:
            - ./data/mongodb:/data/db
        ports:
            - 27017:27017

networks:
    backend:
